### ISSUE TITLE
part file not generated

### ISSUE THREAD

**Issue by GoncaloPT** [Elias8/functional_enum#4]
Hi,
after performing the migration to sound null safety, i noticed that <file>.g.dart was the only file with erros.
After following all the required steps ( including changing imports and pubspec version of functional_enum ) i've realized the part file is not generated anymore.
I don't see any error when I execute the generation using `flutter pub run build_runner build`.  

Excerpts of pubspec.lock:

```
 analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.0"
  build:
    dependency: transitive
    description:
      name: build
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
  build_config:
    dependency: transitive
    description:
      name: build_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.7"
  build_runner_core:
    dependency: transitive
    description:
      name: build_runner_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.2.3"
functional_enum:
    dependency: "direct dev"
    description:
      name: functional_enum
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.4"
  functional_enum_annotation:
    dependency: "direct main"
    description:
      name: functional_enum_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.2"
```
