### ISSUE TITLE
Incompatible dependencies caused by functional_enum

### ISSUE THREAD

**Issue by AlexDochioiu** [Elias8/functional_enum#6]
because freezed 2.1.1 depends on analyzer ^5.0.0 and functional_enum >=1.1.4 depends on analyzer ^2.3.0, freezed ^2.0.0 is incompatible with functional_enum >=1.1.4

The whole pubspec is
```yaml
name: mylib
description: library
version: 0.0.1
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # inner
  core:
    path: "../core"
  cardano_flutter_sdk:
    git:
      url: https://github.com/NFT-Craze/cardano_flutter_sdk.git
      ref: release-v1.0.5
  # streams
  rxdart: ^0.27.4
  # data classes
  freezed_annotation: ^2.0.3
#  functional_enum_annotation: ^1.2.2
  json_annotation: ^4.6.0
  # persistence
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  # others
  uuid: ^3.0.6
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
#  functional_enum: ^1.1.4
  build_runner:

flutter:
```
